### ISSUE TITLE
FAQ Addition

### ISSUE THREAD

**Issue by johndunlap** [WietseWind/xrp-text#4]
My phone is a Google Pixel running Android 9 build PPR2.181005.003 on Verizon. I was unable to send texts to the US number until I added the US number to my contacts. It didn't tell me that that was the problem. It would just say, rather cryptically, "Not sent. Tap to try again." It would be helpful if you added this to your FAQ for people who have the same problem that I did.

**Comment by WietseWind** [comment]
Fixed! Thanks man!
![image](https://user-images.githubusercontent.com/4756161/47835187-e7e84700-dda2-11e8-92a8-0366a820d389.png)

**Comment by johndunlap** [comment]
:)
